targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        # Enable injectable for the whole project
        options:
          generate_for_dir:
            - lib
      injectable_generator:injectable_config_builder:
        options:
          generate_for_dir:
            - lib
